"use client";


import React from 'react'
import TypewriterComponent from 'typewriter-effect';

import { cn } from '@/lib/utils';

import { Poppins } from "next/font/google";
const poppins = Poppins({ weight: "600", subsets: ["latin"] });

type Props = {}

const LandingHero = (props: Props) => {
  return (
    <div >
        <div className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl space-y-5 font-extrabold ">
            <div className=' flex justify-between md:gap-x-9'>
               <svg className='hidden sm:block md:w-1/5 md:h-1/5' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><path fill="#e59d22" d="M21.45 21.31H85.72V85.58H21.45z" transform="rotate(90 53.59 53.45)"></path><path fill="#03081B" d="M85.73 85.59H150V149.86H85.73z" transform="rotate(90 117.865 117.725)"></path><path fill="#212B50" d="M150 150.14H214.26999999999998V214.40999999999997H150z" transform="rotate(90 182.135 182.275)"></path><path fill="#e59d22" d="M214.27 214.41H278.54V278.68H214.27z" transform="rotate(90 246.41 246.55)"></path><path fill="#E8E2D8" d="M21.45 150H85.72V214.26999999999998H21.45z" transform="rotate(90 53.59 182.14)"></path><path fill="#de1e1e" d="M85.73 214.27H150V278.54H85.73z" transform="rotate(90 117.86 246.41)"></path><path fill="#de1e1e" d="M150 21.31H214.26999999999998V85.58H150z" transform="rotate(90 182.14 53.45)"></path><path fill="#E8E2D8" d="M214.27 85.59H278.54V149.86H214.27z" transform="rotate(90 246.41 117.72)"></path></svg>
               <div className=' space-y-11'>
                    <h1 className={cn(' mt-[6rem]', poppins.className)}>Quizzes generated by AI.</h1>
                    <div className=" text-transparent bg-clip-text bg-gradient-to-r from-yellow-500 to-yellow-400">
                    <TypewriterComponent
                        options={{
                        strings: [
                            "Test yourself.",
                            "Trending Topics.",
                            "Unleash the AI.",
                            "Score More."
                        ],
                        autoStart: true,
                        loop: true,
                        }}
                    />
                    </div>

                    <div className=" text-sm md:text-xl font-light text-zinc-400">
                        Explore your favourite topics and Expand your knowledge.
                    </div>

               </div>
               <svg className='hidden sm:block md:w-1/5 md:h-1/5' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 300"><path fill="#de1e1e" d="M177.97 300H0V180.49h96.48c10.56 0 20.32 5.64 25.6 14.78l51.93 89.95c2.64 4.58 3.96 9.68 3.96 14.78z"></path><path fill="#e59d22" d="M300 30.49v239.02h-53.09c-10.56 0-20.32-5.64-25.6-14.78l-51.93-89.95a29.562 29.562 0 010-29.56l51.93-89.95a29.573 29.573 0 0125.6-14.78H300z"></path><path fill="#212B50" d="M171.85 0c0 5.1-1.32 10.2-3.96 14.78l-51.93 89.95a29.573 29.573 0 01-25.6 14.78H0V0h171.85z"></path></svg>
            </div>
            
          </div>
    </div>
  )
}

export default LandingHero